INSERT INTO MEMBER (MEM_ID, MEM_ACCOUNT, MEM_EMAIL, MEM_INFO_AGREE,MEM_NAME, MEM_PASSWORD, MEM_PROFILE, MEM_PROFILE_LOC,MEM_REGISTER_DATE, MEM_STATUS) VALUES (1,'id1234','ijd1234@gmail.com',true,'쩐시','1234','temp','temp',CURRENT_TIMESTAMP(),true);
INSERT INTO MEMBER (MEM_ID, MEM_ACCOUNT, MEM_EMAIL, MEM_INFO_AGREE,MEM_NAME, MEM_PASSWORD, MEM_PROFILE, MEM_PROFILE_LOC,MEM_REGISTER_DATE, MEM_STATUS) VALUES (2,'sfssfs','zzc34@gmail.com',true,'튜브','1234','temp','temp',CURRENT_TIMESTAMP(),true);
--INSERT INTO GROUPS (GROUP_ID,GROUP_NAME,CREATED_AT,GROUP_STATUS,GROUP_CONTENTS)VALUES(1,'aaa',CURRENT_TIMESTAMP,TRUE,'aaa');
INSERT INTO SET_IN_GROUP(GROUP_SET_ID,GROUP_SET_NAME,GROUP_SET_CREATED_AT)VALUES (1,'We Bare Bears Cleanse',CURRENT_TIMESTAMP);
INSERT INTO SET_IN_GROUP(GROUP_SET_ID,GROUP_SET_NAME,GROUP_SET_CREATED_AT)VALUES (2,'We Bare Bears Cleanse2',CURRENT_TIMESTAMP);
INSERT INTO SET_IN_GROUP(GROUP_SET_ID,GROUP_SET_NAME,GROUP_SET_CREATED_AT)VALUES (3,'We Bare Bears Cleanse3',CURRENT_TIMESTAMP);
INSERT INTO SET_IN_GROUP(GROUP_SET_ID,GROUP_SET_NAME,GROUP_SET_CREATED_AT)VALUES (4,'We Bare Bears Cleanse4',CURRENT_TIMESTAMP);
--INSERT INTO WORD_IN_GROUP(GROUP_WORD_ID,GROUP_WORD_NAME,GROUP_WORD_MEAN,GROUP_WORD_PHOTO,GROUP_WORD_PHOTO_LOC)VALUES(1,'So you''re here for a checkup? Tell me, do you have any allergies?','013. 네, 여러분들 건강검진 받으러 온건 가요? /// 제게 말씀해주세요 / 알레르기 있는 분?','temp','temp');
