INSERT INTO MEMBER (MEMBER_ID, MEMBER_ACCOUNT, MEMBER_EMAIL, MEMBER_INFO_AGREE,MEMBER_NAME, MEMBER_PASSWORD, MEMBER_PROFILE, MEMBER_PROFILE_LOCATION,MEMBER_REGISTER_DATE, MEMBER_STATUS) VALUES (1,'id1234','ijd1234@gmail.com',true,'쩐시','1234','temp','temp',CURRENT_TIMESTAMP(),true);


